-- AlterTable
ALTER TABLE "CorrectAnswer" ADD COLUMN     "playDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Player" ADD COLUMN     "playDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
